---
abstract: 'mysqld runner for tests'
author:
  - 'Cybozu Labs, Inc.  Written by Kazuho Oku.'
build_requires:
  Test::More: '0'
  Test::SharedFork: '0'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.1.23, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-mysqld
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Test::mysqld:
    file: lib/Test/mysqld.pm
    version: '1.0020'
requires:
  Class::Accessor::Lite: '0'
  DBD::mysql: '0'
  DBI: '0'
  File::Copy::Recursive: '0'
  File::Temp: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/kazuho/p5-test-mysqld/issues
  homepage: https://github.com/kazuho/p5-test-mysqld
  repository: https://github.com/kazuho/p5-test-mysqld.git
version: '1.0020'
x_authority: cpan:KAZUHO
x_contributors:
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'FUJIWARA Shunichiro <fujiwara.shunichiro@gmail.com>'
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'Ichinose Shogo <shogo82148@gmail.com>'
  - 'Jason Galea <jason@lecstor.com>'
  - 'Johan Lindstrom <johan.lindstrom@broadbean.com>'
  - 'John Napiorkowski <jjn1056@yahoo.com>'
  - 'Kazuho Oku <kazuho@li1.kazuhooku.com>'
  - 'Kazuho Oku <kazuhooku@gmail.com>'
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
  - 'Matthew Horsfall <wolfsage@gmail.com>'
  - 'NAKAGAWA Masaki <masaki.nakagawa@gmail.com>'
  - 'Naoto Nakamura <naoto.nakamura@showroom.co.jp>'
  - 'Petr Písař <ppisar@redhat.com>'
  - 'Yoshikazu Sawa <883514+yoshikazusawa@users.noreply.github.com>'
  - 'Yusuke Watase <ywatase@gmail.com>'
  - 'Zhenjun Wang <zjwang0414@gmail.com>'
  - 'hiratara <hiratara@cpan.org>'
  - 'karupanerura <karupa@cpan.org>'
  - 'lestrrat <lestrrat+github@gmail.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
